In [5]:
# see https://ipython.readthedocs.io/en/stable/interactive/magics.html
%pylab inline

%config InlineBackend.figure_formats = ['svg']

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import stats 
import math

Populating the interactive namespace from numpy and matplotlib

In [6]:
data = pd.read_csv('https://raw.githubusercontent.com/quyetzz/Analysis-of-university-exam-scores-in-2019-2020/main/clean_data.csv')

In [7]:
data

,sbd,tên,dd,mm,yy,toán,ngữ văn,khxh,khtn,lịch sử,địa lí,gdcd,sinh học,vật lí,hóa học,tiếng anh
0,2000001,Phạm Hoàng Hương Ái,4,11,2002,6.6,6.25,6.67,-1.00,5.75,7.00,7.25,-1.00,-1.00,-1.00,5.2
1,2000002,Đặng Huỳnh Vĩnh An,13,12,2002,8.2,7.75,7.58,-1.00,7.00,7.25,8.50,-1.00,-1.00,-1.00,7.0
2,2000003,Lâm Nguyễn Mộng Thùy An,6,4,2001,6.8,6.75,6.92,-1.00,4.75,7.75,8.25,-1.00,-1.00,-1.00,6.0
3,2000004,Lê Tiêu Hoàng An,18,11,2002,7.8,6.25,-1.00,6.25,-1.00,-1.00,-1.00,7.00,5.50,6.25,5.6
4,2000005,Lư Thuận An,14,1,2002,6.4,6.50,-1.00,6.17,-1.00,-1.00,-1.00,5.50,6.75,6.25,8.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74439,2074714,Nguyễn Đình Hải Yến,10,11,2002,5.4,5.92,-1.00,4.67,-1.00,-1.00,-1.00,5.50,3.50,5.00,-1.0
74440,2074715,Nguyễn Thị Hải Yến,5,5,2002,8.6,7.00,-1.00,7.92,-1.00,-1.00,-1.00,6.75,8.25,8.75,6.2
74441,2074716,Nguyễn Trần Tiểu Yến,7,10,2002,9.2,7.50,-1.00,8.50,-1.00,-1.00,-1.00,8.25,8.75,8.50,6.2
74442,2074717,Phạm Thị Kim Yến,20,11,2002,9.0,7.00,-1.00,8.00,-1.00,-1.00,-1.00,6.75,8.00,9.25,7.0
74443,2074718,Văn Hồng Yến,27,10,2002,5.6,6.50,-1.00,-1.00,6.50,7.25,-1.00,-1.00,-1.00,-1.00,-1.0

In [8]:
data.columns = ['sbd','name','dd','mm','yy','math','literature','khtn','khxh','history','Geographic','gdcd','chemical','physics','biology','english']

In [9]:
data

,sbd,name,dd,mm,yy,math,literature,khtn,khxh,history,Geographic,gdcd,chemical,physics,biology,english
0,2000001,Phạm Hoàng Hương Ái,4,11,2002,6.6,6.25,6.67,-1.00,5.75,7.00,7.25,-1.00,-1.00,-1.00,5.2
1,2000002,Đặng Huỳnh Vĩnh An,13,12,2002,8.2,7.75,7.58,-1.00,7.00,7.25,8.50,-1.00,-1.00,-1.00,7.0
2,2000003,Lâm Nguyễn Mộng Thùy An,6,4,2001,6.8,6.75,6.92,-1.00,4.75,7.75,8.25,-1.00,-1.00,-1.00,6.0
3,2000004,Lê Tiêu Hoàng An,18,11,2002,7.8,6.25,-1.00,6.25,-1.00,-1.00,-1.00,7.00,5.50,6.25,5.6
4,2000005,Lư Thuận An,14,1,2002,6.4,6.50,-1.00,6.17,-1.00,-1.00,-1.00,5.50,6.75,6.25,8.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74439,2074714,Nguyễn Đình Hải Yến,10,11,2002,5.4,5.92,-1.00,4.67,-1.00,-1.00,-1.00,5.50,3.50,5.00,-1.0
74440,2074715,Nguyễn Thị Hải Yến,5,5,2002,8.6,7.00,-1.00,7.92,-1.00,-1.00,-1.00,6.75,8.25,8.75,6.2
74441,2074716,Nguyễn Trần Tiểu Yến,7,10,2002,9.2,7.50,-1.00,8.50,-1.00,-1.00,-1.00,8.25,8.75,8.50,6.2
74442,2074717,Phạm Thị Kim Yến,20,11,2002,9.0,7.00,-1.00,8.00,-1.00,-1.00,-1.00,6.75,8.00,9.25,7.0
74443,2074718,Văn Hồng Yến,27,10,2002,5.6,6.50,-1.00,-1.00,6.50,7.25,-1.00,-1.00,-1.00,-1.00,-1.0

In [24]:
from scipy.stats import binom
  
print (1 - binom.cdf(data['math'],10, 0.95))
print (binom.cdf(data['math'],10, 0.05))

[0.9989715  0.91386164 0.9989715  ... 0.59873694 0.59873694 0.99993631]
[0.99999992 1.         0.99999992 ... 1.         1.         0.99999725]